# Generated by Django 5.1.1 on 2024-09-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_subtitulo_pessoal_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoal',
            name='parentesco',
            field=models.CharField(max_length=20),
        ),
    ]
