# Generated by Django 5.1.1 on 2024-09-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_pessoal_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoal',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
    ]
