# Generated by Django 5.1.1 on 2024-09-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_pessoal_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotina',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
