# Generated by Django 5.1.1 on 2024-09-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_gostos_imagem_alter_gostos_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoal',
            name='parentesco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
