# Generated by Django 5.1.1 on 2024-09-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_pessoal_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gostos',
            name='descricao',
            field=models.TextField(blank=True, default='Escreva sua descrição'),
        ),
        migrations.AlterField(
            model_name='gostos',
            name='titulo',
            field=models.CharField(blank=True, default='Escreva sua descrição', max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='descricao',
            field=models.TextField(blank=True, default='Escreva sua descrição'),
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='nome',
            field=models.CharField(blank=True, default='Escreva sua descrição', max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='parentesco',
            field=models.CharField(blank=True, default='Escreva sua descrição', max_length=100),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='descricao',
            field=models.TextField(blank=True, default='Escreva sua descrição'),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='titulo',
            field=models.CharField(blank=True, default='Escreva sua descrição', max_length=100),
        ),
    ]
