# Generated by Django 5.1.1 on 2024-09-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_pessoal_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoal',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='parentesco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
