# Generated by Django 5.1.1 on 2024-09-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_pessoal_descricao_alter_pessoal_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gostos',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gostos',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
